In [ ]:

import numpy as np
f=np.array([32,100,323,0])
c=((f-32)*5)/9
print(c)

[  0.          37.77777778 161.66666667 -17.77777778]


In [ ]:
import random 

a=np.random.randint(0,1000,size=1000)
print(a)
average=np.mean(a)
variance=np.var(a)
std=np.std(a)
print(average)
print(variance)
print(std)


[ 94 839 600 685 266 415 449 554 943 196  13 151 253 157 265 542 698 671
 565  37 690 916 117 796 852 721 536 640 993 274 344 626 824 512  99 767
 834 988 413 571 149 226 623 104 124 465 329 521 188 652  57 353 212 848
 634 419 316 500 741 594 787 161 373 291 855 150 828 400 669 291 211   6
 963 927  71 594 497 150 812 167  41 306  23  13 675 665 681 419 199 662
 839  18 735 753 493 402 593 459 568 605 945 950 615 926  48 215 623 732
 818 716 969 119 561 307 680 745 522 258 647 827 795 623 675 329 273 876
 434 641 218 158 523 611 347 791 226  47 351 425 903 934 188 422 245 619
 474 957 640 352 658 561 494  71 149 315 988 390 580 707 307 389 405 283
 628 292  69 776 663 723 831 500 614 769 338 499 340 596 362 596 160 901
 300 557 411 895   5 816 295 807 684 695 939 914 927 155 401 636 564 767
 853 978 398 519 140 919 491 295 774 351 906 887 308 505  95  31 231 109
 465 984 998 199 370 696 404 228 794 965 761 517 682  49 640 419 647 128
 970 479  78 663 695  93   7 652 584  34 584 705  6

In [39]:
degree=np.array([20,30,50,40])
radians=np.deg2rad(degree)
print(radians)

[0.34906585 0.52359878 0.87266463 0.6981317 ]


In [42]:
arr=np.array([1,30,56,10,66])
print(arr)
differ=np.diff(arr)
print(differ)

[ 1 30 56 10 66]
[ 29  26 -46  56]


In [84]:
complex_array=np.array([1+2j,3+4j,9+6j,0+8j,9+3j])
sorted_array=complex_array[np.lexsort((complex_array.imag,complex_array.real)).astype(int)]
print(complex_array)
print(sorted_array)

[1.+2.j 3.+4.j 9.+6.j 0.+8.j 9.+3.j]
[0.+8.j 1.+2.j 3.+4.j 9.+3.j 9.+6.j]


In [83]:
a=np.random.randint(1,20,size=10)
print(a)
b=int(input("enter number to search: "))
x=np.where(a==b)
print(x)
if(len(x[0])==0):
    print("element not found")
else:
    print("Element found at: ",x[0]+1)


[15  5 18  1 12 10  1 14 17  6]
(array([3, 6], dtype=int64),)
Element found at:  [4 7]


In [59]:
import numpy as np
number=np.random.randint(1,15,size=6)
print(number)
print(number[number>4])



[11  4  4  5 12  9]
[11  5 12  9]


In [65]:
even=np.arange(30,61,2)
print(even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [69]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
total=np.sum(array)
col_sum=np.sum(array,axis=0)
row_sum=np.sum(array,axis=1)
print(total)
print(col_sum)
print(row_sum)


45
[12 15 18]
[ 6 15 24]


In [85]:
arr=np.array([1,4,6,8,2])
np.savetxt("array.txt",arr)
load=np.loadtxt("array.txt")
print("original",arr)
print("loaded",load.astype(int))

original [1 4 6 8 2]
loaded [1 4 6 8 2]
