In [1]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(np.transpose(matrix))
print(np.trace(matrix))
matrix1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix1)
print(np.dot(matrix,matrix1))
print(np.linalg.inv(matrix))
print(np.linalg.matrix_rank(matrix))
print("Eigen Values & Eigen Vectors: ",np.linalg.eig(matrix))
print("Eigen Values: ",np.linalg.eigvals(matrix))




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
15
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
2
Eigen Values & Eigen Vectors:  EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
Eigen Values:  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


: 