In [1]:
import numpy as np
a=(1,2,3,4)
type(a)

tuple

In [3]:
b=np.array(a)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

In [5]:
c=[1,2,3]
type(c)
print(type(c))
d=np.array(c)
print(type(d))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
s=np.arange(10)
print(s)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
e=np.arange(2,100,2)
print(e)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [12]:
f=np.arange(1,100,2)
print(f)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [16]:
f=np.zeros(5,int)
print(f)

[0 0 0 0 0]


In [17]:
f=np.ones(10,int)
print(f)

[1 1 1 1 1 1 1 1 1 1]


In [19]:
f=np.ones((3,3),int)
print(f)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
y=np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
y=np.identity(5,int)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [25]:
r=np.absolute(-4.676)
print(r)

4.676


In [27]:
r=[1,2,3,4,5,6,7,8]
print(r[:3])

[1, 2, 3]


In [32]:
d=np.arange(1,16)
print(d[:12])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
d=np.array([3,17,2])
print(d[1:])

[17  2]


In [39]:
d=np.arange(3,17,3)
print(d)
b=np.copy(d)
print("b=",b)

[ 3  6  9 12 15]
b= [ 3  6  9 12 15]


In [40]:
d=np.arange(3,17,3)
print(d)
arr=d
print(arr)
d[2]=11
print(d)
print(arr)

[ 3  6  9 12 15]
[ 3  6  9 12 15]
[ 3  6 11 12 15]
[ 3  6 11 12 15]


In [59]:
d=np.arange(10)
print(d)

new=d.view()
print(new)
d[2]=0
print(d)
print(new)



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 0 3 4 5 6 7 8 9]
[0 1 0 3 4 5 6 7 8 9]


In [45]:
a=np.arange(3,8,1)
b=np.arange(4,10,2)
print(a)
print(b)
c=np.concatenate((a,b))
print(c)

[3 4 5 6 7]
[4 6 8]
[3 4 5 6 7 4 6 8]


In [60]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("a=",a)
print("b=",b)
c=np.concatenate((a,b),axis=0)
print("c=",c)

a= [[1 2]
 [3 4]]
b= [[5 6]
 [7 8]]
c= [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:

e=np.array((3,4,4,5,6))
x=np.where(e==6)
print(*x[0])
if(len(x[0])==0):
    print("not found")
else:
    print("found at ",*x[0]+1)


4
found at  5
